### ISSUE TITLE
file extension names

### ISSUE THREAD

**Issue by sdarwin** [capgelka/lcov-diff#2]
`gcov` creates files with extensions `.gcno`, or .`gcda`.   

`lcov-diff` doesn't directly process or use `.gcno`, or .`gcda` files, correct?

In the lcov example at https://ltp.sourceforge.net/coverage/lcov.php the generated file is named `coverage.info.`  If searching the internet for lcov examples, there are many cases of the `.info` extension.   However, not as much with `.lcov` extension.   

When you use `.lcov `in the README file is that the same type of file as a `.info` file?     I think it is, but just confirming.

**Comment by capgelka** [comment]
I thought `.info` is not very informative so changed the name in the example to make things clearer however, your issue shows that the result is the opposite. So I'll change this.
