### ISSUE TITLE
Error: UnmatchedFunctionLine

### ISSUE THREAD

**Issue by sdarwin** [capgelka/lcov-diff#3]
Hi,
We have a C++ codebase, and process code coverage using lcov.   The generated file is `coverage.info` . 

If I build a different commit from a year ago when the code was significantly different, and produce another `coverage.info`, then I could compare them with `lcov-diff` :

```
$ lcov-diff coverage.info ../other/coverage.info 
[2022-12-07T23:13:49Z INFO  lcov_diff] Processing diff for two lcov files: ["coverage.info", "../other/coverage.info"]
Error: UnmatchedFunctionLine
```

Maybe there have been too many changes.
So, try the same process again, but with a recent commit, that hasn't varied much.

Same issue:
`Error: UnmatchedFunctionLine`

What might be the cause? If new "functions" or "lines" or "files" are added, or removed, will that break `lcov-diff`?     Or something else...

**Comment by capgelka** [comment]
The `lcov-diff` purpose is not to see how the coverage of your test suite changes according to changes in the source code. It's to compare the coverage of 2 tests suits on the same code.

> If new "functions" or "lines" or "files" are added, or removed, will that break lcov-diff

So yes, it will.


In theory, it's possible to do what you want. One should take the diff of source code versions and somehow patch the `lcov` report according to the source code changes. And then you can use `lcov-diff` with the patched one repor. 
After a brief search, I have not found the tool which is able to do this. But maybe it exists.

**Comment by sdarwin** [comment]
Well, that's interesting.   Approaching the problem from the perspective that we'd like to diff pull requests, and observe if the pull request is causing more or less code coverage (similar to a codecov chart), I am not even sure about your chosen use case of diffing the exact same set of files.  I will test out https://github.com/zachriggle/covpare pretty soon also and see what features that has or doesn't have.

**Comment by sdarwin** [comment]
Looks like `gcovr --json-summary` will output coverage data as json, and from there it shouldn't be overly difficult to run comparisons.
